apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aewi-cluster-stress-psp
rules:
  - apiGroups:
    - extensions
    resources:
    - podsecuritypolicies
    verbs:
    - use
    resourceNames:
    - aewi-cluster-stress-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aewi-cluster-stress-psp
subjects:
  - kind: ServiceAccount
    name: aewi-cluster-stress
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: aewi-cluster-stress-psp
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aewi-cluster-stress
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: aewi-cluster-stress-psp
spec:
  allowPrivilegeEscalation: true
  fsGroup:
    rule: RunAsAny
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - 'secret'
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: aewi-cluster-stress
  namespace: kube-system
  labels:
    app: aewi-cluster-stress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aewi-cluster-stress
    spec:
      serviceAccount: aewi-cluster-stress
      securityContext:
        runAsUser: 0
      containers:
        - name: aewi-cluster-stress
          image: docker.io/cpate3/aewi-cluster-stress:latest
