apiVersion: v1
kind: Service
metadata:
  name: hello-runtime-cpate3
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-runtime-cpate3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-runtime-cpate3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-runtime-cpate3
  template:
    metadata:
      labels:
        app: hello-runtime-cpate3
    spec:
      containers:
      - name: runtime-test-cpate3
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello from the first runtime web app!
